
title: Rethinking Intelligence
email: robertdtodd@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
 Rethinking Intelligence is a site dedicated to promoting understanding of artifical intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robertdtodd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: robertdtodd
github_username:  robertdtodd

header_pages:
 - resources.md
 - experiments.md
 - about.md

include: ["_pages"]

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

minimal_mistakes_skin: 
  - "air"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      share: true
      related: true

date_format: "%Y-%b-%d"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
